
[Dataset-ID]
scope = "Public"
group = "Name of research group or data repository"
title = "This is a short title"
description = """\
	This is a description of the experiment or study, \
	including the purpose why the data was collected, \
	and the overall goals of the research project.\
	"""
sample-processing = """\
	This section describes the sample preparation and \
	the data collection protocol.\
	"""
data-processing = """\
	This section describes any computational processing \
	applied to the data or files.\
	"""
contact = [
	{name = "Bad Wolf", email = "entity@the-moment.time"}
]
url.doi = "not.a.valid.doi/or.is.it"
url.pub = "bad.wolf.corporation"
date.created = "1 Jan 1970"
date.received = "1 Jan 1970"
formats = []
keywords = ["documentation"]
notes = [
	"Fields scope, group, title, description are required",
	"Everything else is optional (but strongly recommended)."]

[Example-1]
scope = "Private"
group = "Bad Wolf Corporation"
title = "Example private dataset"
description = """\
	This dataset should not be shared or published.\
	"""
contact = [
	{name = "Bad Wolf", email = "entity@the-moment.time"}
]
keywords = ["secret", "meme"]
notes = ["I am the Bad Wolf."]

[Example-2]
scope = "Protected"
group = "Bad Wolf Corporation"
title = "Example protected dataset"
description = """\
	This dataset requires permission to be shared or published.\
	"""
contact = [
	{name = "Bad Wolf", email = "entity@the-moment.time"}
]
keywords = ["secret", "meme"]
notes = ["I create myself."]

[Example-3]
scope = "Public"
group = "Bad Wolf Corporation"
title = "Example public dataset"
description = """\
	This dataset is safe to publish and share widely.\
	"""
contact = [
	{name = "Bad Wolf", email = "entity@the-moment.time"}
]
keywords = ["bootstrap", "paradox"]
notes = [
	"I take the words, I scatter them in time and space.",
	"A message to lead myself here."]
